FROM spcleth/mignificient:base AS iceoryx-builder

RUN apt-get update && apt-get install -y \
    libacl1-dev \
    && rm -rf /var/lib/apt/lists/*\
    && curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain 1.88 -y


# Build iceoryx v1 from local source (with patches applied)
COPY external/iceoryx.patch /src/iceoryx.patch
RUN git clone https://github.com/eclipse-iceoryx/iceoryx.git /src/iceoryx \
    && cd /src/iceoryx && git checkout 83798774098a6ca2931be0452a1840aefb65f3c6 \
    && git apply /src/iceoryx.patch || true \
    && cmake -B build -S iceoryx_meta \
      -DCMAKE_INSTALL_PREFIX=/opt/iceoryx \
      -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_SHARED_LIBS=ON \
    && cmake --build build -j$(nproc) \
    && cmake --install build

# Build iceoryx2 from source
RUN apt-get update && apt-get install -y clang libclang-dev && rm -rf /var/lib/apt/lists/*
RUN . $HOME/.bashrc && git clone https://github.com/eclipse-iceoryx/iceoryx2.git /src/iceoryx2 \
    && cd /src/iceoryx2 \
    && cmake -B build -S . \
      -DCMAKE_INSTALL_PREFIX=/opt/iceoryx2 \
      -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_SHARED_LIBS=ON \
    && cmake --build build -j$(nproc) \
    && cmake --install build

FROM spcleth/mignificient:base

COPY --from=iceoryx-builder /opt/iceoryx /opt/iceoryx
COPY --from=iceoryx-builder /opt/iceoryx2 /opt/iceoryx2
